#!/usr/bin/env python3
"""Interactive setup for the Synology MCP server.

Run this once after cloning. It will:
  1. create a virtual environment and install the package,
  2. ask for your NAS URL / username / password and write a local .env,
  3. test the connection (and walk you through 2FA if needed),
  4. register the server in your Claude Desktop config (with a backup), and
  5. print the command for Claude Code.

Nothing is sent anywhere except to your NAS. Credentials are stored only in the
local .env file. Run with any Python 3.11+:

    python3 configure.py
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import sys
import time
from getpass import getpass
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"


def c(txt: str, color: str) -> str:
    codes = {"b": "1", "green": "32", "yellow": "33", "red": "31", "cyan": "36", "dim": "2"}
    if not sys.stdout.isatty():
        return txt
    return f"\033[{codes.get(color, '0')}m{txt}\033[0m"


def step(n: int, total: int, title: str) -> None:
    print(f"\n{c(f'[{n}/{total}]', 'cyan')} {c(title, 'b')}")


def venv_python() -> Path:
    if platform.system() == "Windows":
        return ROOT / ".venv" / "Scripts" / "python.exe"
    return ROOT / ".venv" / "bin" / "python"


def claude_desktop_config_path() -> Path:
    home = Path.home()
    sysname = platform.system()
    if sysname == "Darwin":
        return home / "Library" / "Application Support" / "Claude" / "claude_desktop_config.json"
    if sysname == "Windows":
        return Path(os.environ.get("APPDATA", home)) / "Claude" / "claude_desktop_config.json"
    return home / ".config" / "Claude" / "claude_desktop_config.json"


# ── steps ──────────────────────────────────────────────────────────────────────

def ensure_venv() -> Path:
    step(1, 5, "Virtual environment & dependencies")
    py = venv_python()
    if not py.exists():
        print("  Creating .venv ...")
        subprocess.run([sys.executable, "-m", "venv", str(ROOT / ".venv")], check=True)
    print("  Installing the package (pip install -e .) ...")
    subprocess.run([str(py), "-m", "pip", "install", "-q", "--upgrade", "pip"], check=True)
    subprocess.run([str(py), "-m", "pip", "install", "-q", "-e", str(ROOT)], check=True)
    print(c("  ✓ Environment ready", "green"))
    return py


def gather_credentials() -> dict:
    step(2, 5, "NAS connection details")
    if ENV_PATH.exists():
        keep = input(f"  {ENV_PATH.name} already exists. Overwrite it? [y/N] ").strip().lower()
        if keep != "y":
            print(c("  Keeping existing .env", "dim"))
            return {}
    print("  Example URL: http://192.168.1.100:5000  (or https://…:5001)")
    url = input("  NAS URL: ").strip().rstrip("/")
    user = input("  Username: ").strip()
    password = getpass("  Password (hidden): ")
    return {"SYNOLOGY_URL": url, "SYNOLOGY_USER": user, "SYNOLOGY_PASS": password}


def write_env(values: dict) -> None:
    if not values:
        return
    lines = [
        "# Generated by configure.py — keep this file private (it is git-ignored).",
        f"SYNOLOGY_URL={values['SYNOLOGY_URL']}",
        f"SYNOLOGY_USER={values['SYNOLOGY_USER']}",
        f"SYNOLOGY_PASS={values['SYNOLOGY_PASS']}",
        "SYNOLOGY_DEVICE_ID=",
    ]
    if ENV_PATH.exists():
        shutil.copy(ENV_PATH, ENV_PATH.with_suffix(f".bak.{int(time.time())}"))
    ENV_PATH.write_text("\n".join(lines) + "\n")
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass
    print(c(f"  ✓ Wrote {ENV_PATH.name}", "green"))


def test_connection(py: Path) -> bool:
    step(3, 5, "Testing the connection")
    result = subprocess.run([str(py), str(ROOT / "smoke_test.py")],
                            capture_output=True, text=True)
    out = result.stdout + result.stderr
    print("  " + out.strip().replace("\n", "\n  "))
    if result.returncode == 0:
        print(c("  ✓ Connection OK", "green"))
        return True
    if "403" in out or "2FA" in out or "OTP" in out or "406" in out:
        print(c("  This account uses two-factor authentication.", "yellow"))
        otp = input("  Enter the current 6-digit code from your authenticator: ").strip()
        if otp:
            b = subprocess.run([str(py), str(ROOT / "bootstrap_2fa.py"), otp],
                               capture_output=True, text=True)
            print("  " + (b.stdout + b.stderr).strip().replace("\n", "\n  "))
            if b.returncode == 0:
                return test_connection(py)
    print(c("  ✗ Connection failed — check the details above and re-run.", "red"))
    return False


def configure_claude_desktop(py: Path) -> None:
    step(4, 5, "Claude Desktop")
    cfg_path = claude_desktop_config_path()
    ans = input(f"  Add the server to Claude Desktop config?\n    {cfg_path}\n  [Y/n] ").strip().lower()
    if ans == "n":
        print(c("  Skipped.", "dim"))
        return
    cfg = {}
    if cfg_path.exists():
        try:
            cfg = json.loads(cfg_path.read_text())
        except json.JSONDecodeError:
            print(c("  Existing config isn't valid JSON — not touching it.", "red"))
            return
        shutil.copy(cfg_path, cfg_path.with_suffix(f".json.bak.{int(time.time())}"))
        print(c("  ✓ Backed up existing config", "green"))
    else:
        cfg_path.parent.mkdir(parents=True, exist_ok=True)

    cfg.setdefault("mcpServers", {})["synology"] = {
        "command": str(py),
        "args": ["-m", "synology_mcp"],
        "env": {"PYTHONPATH": str(ROOT)},
    }
    cfg_path.write_text(json.dumps(cfg, indent=2, ensure_ascii=False))
    print(c(f"  ✓ Registered 'synology' in {cfg_path.name}", "green"))
    print(c("  → Fully quit and reopen Claude Desktop to load it.", "yellow"))


def print_claude_code(py: Path) -> None:
    step(5, 5, "Claude Code (optional)")
    print("  To use it in Claude Code instead, run:")
    print(c(f"    claude mcp add synology -- {py} -m synology_mcp", "cyan"))


def main() -> None:
    print(c("\n  Synology MCP — setup\n  ====================", "b"))
    if sys.version_info < (3, 11):
        print(c(f"  Python 3.11+ required (you have {platform.python_version()}).", "red"))
        sys.exit(1)
    try:
        py = ensure_venv()
        values = gather_credentials()
        write_env(values)
        ok = test_connection(py)
        if ok:
            configure_claude_desktop(py)
            print_claude_code(py)
            print(c("\n  ✅ All done. Enjoy!\n", "green"))
        else:
            print(c("\n  Fix the connection and re-run: python3 configure.py\n", "yellow"))
    except KeyboardInterrupt:
        print("\n  Cancelled.")
    except subprocess.CalledProcessError as e:
        print(c(f"\n  A setup command failed: {e}", "red"))
        sys.exit(1)


if __name__ == "__main__":
    main()
